### ISSUE TITLE
sozo build fail : thread 'main' panicked at 'not yet implemented:

### ISSUE THREAD

**Issue by Minusbill** [dojoengine/dojo-examples#27]
if I am 
dojo = { git = "https://github.com/dojoengine/dojo", version = "0.3.1" }

❯ sozo build
    Updating git repository https://github.com/dojoengine/dojo
thread 'main' panicked at 'not yet implemented: Registry sources are not implemented yet.', /Users/runner/.cargo/git/checkouts/scarb-831c32bf23da0a7c/7adb7fd/scarb/src/core/source/id.rs:228:37

if i use 

❯ sozo build
    Updating git repository https://github.com/dojoengine/dojo
   Compiling dojo_examples v0.3.1 (/Users/billtc/my-project/mydojo/dojo-starter/Scarb.toml)
    Finished release target(s) in 4 seconds

i want to know the problem

**Comment by ponderingdemocritus** [comment]
What dojoup version are you on?

**Comment by Minusbill** [comment]
> What dojoup version are you on?

0.3.1

**Comment by ponderingdemocritus** [comment]
where are you trying to compile?

**Comment by Minusbill** [comment]
dojo-starter

> where are you trying to compile?

https://github.com/dojoengine/dojo-starter

in the dojo-starter

**Comment by Minusbill** [comment]
> where are you trying to compile?

if i upgrade the dojo to 0.3.1 , it appears
